services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=cmapesa56@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - traefik_network

  frontend:
    build: ./frontend
    env_file:
      - .env
    depends_on:
      - auth-api
      - todos-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`cliffordmapesa.online`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  auth-api:
    build: ./auth-api
    env_file:
      - .env
    depends_on:
      - users-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.cliffordmapesa.online`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=myresolver"
      - "traefik.http.routers.auth-api.rule=Host(`cliffordmapesa.online`) && PathPrefix(`/api/auth`)"
      - "traefik.http.routers.auth-api.entrypoints=websecure"
      - "traefik.http.routers.auth-api.tls.certresolver=myresolver"

  todos-api:
    build: ./todos-api
    env_file:
      - .env
    depends_on:
      - redis-queue
      - log-message-processor
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todos.rule=Host(`todos.cliffordmapesa.online`)"
      - "traefik.http.routers.todos.entrypoints=websecure"
      - "traefik.http.routers.todos.tls.certresolver=myresolver"
      - "traefik.http.routers.todos-api.rule=Host(`cliffordmapesa.online`) && PathPrefix(`/api/todos`)"
      - "traefik.http.routers.todos-api.entrypoints=websecure"
      - "traefik.http.routers.todos-api.tls.certresolver=myresolver"

  users-api:
    build: ./users-api
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=Host(`users.cliffordmapesa.online`)"
      - "traefik.http.routers.users.entrypoints=websecure"
      - "traefik.http.routers.users.tls.certresolver=myresolver"
      - "traefik.http.routers.users-api.rule=Host(`cliffordmapesa.online`) && PathPrefix(`/api/users`)"
      - "traefik.http.routers.users-api.entrypoints=websecure"
      - "traefik.http.routers.users-api.tls.certresolver=myresolver"

  log-message-processor:
    build: ./log-message-processor
    env_file:
      - .env
    depends_on:
      - redis-queue

  redis-queue:
    image: redis:7
    volumes:
      - redis_data:/data
    restart: always

networks:
  traefik_network:
    driver: bridge

volumes:
  redis_data:
